// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714083405_StatusToNumber")]
    partial class StatusToNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("address_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("DetailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("detail_address");

                    b.Property<int>("IsDefault")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("user_id");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("address");
                });

            modelBuilder.Entity("Backend.Models.AdminUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("user_id");

                    b.Property<int>("Permission")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("permission");

                    b.HasKey("UserId");

                    b.ToTable("admin_user");
                });

            modelBuilder.Entity("Backend.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("announcement_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("admin_id");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("info");

                    b.Property<DateTime>("ReleaseTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("release_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("title");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("AdminId");

                    b.ToTable("announcement");
                });

            modelBuilder.Entity("Backend.Models.BaseUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("user_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<long?>("AvatarFileId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("avatar_file_id");

                    b.Property<DateTime?>("BannedUntil")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("banned_until");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("gender");

                    b.Property<int>("IsBanned")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_banned");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("pw_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime>("RegisterTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("register_time");

                    b.Property<int>("UserType")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("user_type");

                    b.HasKey("UserId");

                    b.HasIndex("AvatarFileId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("\"phone_number\" IS NOT NULL");

                    b.ToTable("base_user");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("category_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("category_name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("parent_id");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentId");

                    b.ToTable("category");
                });

            modelBuilder.Entity("Backend.Models.Collection", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("product_id")
                        .HasColumnOrder(0);

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CollectionTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("collection_time");

                    b.HasKey("ProductId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("collection");
                });

            modelBuilder.Entity("Backend.Models.Conversation", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("session_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("create_time");

                    b.Property<long>("ProductId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("product_id");

                    b.HasKey("SessionId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ProductId");

                    b.ToTable("conversation");
                });

            modelBuilder.Entity("Backend.Models.Message", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("session_id")
                        .HasColumnOrder(0);

                    b.Property<int>("MsgIndex")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("msg_index")
                        .HasColumnOrder(1);

                    b.Property<long?>("FileId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("file_id");

                    b.Property<int>("IsRead")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_read");

                    b.Property<string>("MsgContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("msg_content");

                    b.Property<int>("MsgType")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("msg_type");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("send_time");

                    b.Property<int>("SenderId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("sender_id");

                    b.HasKey("SessionId", "MsgIndex");

                    b.HasIndex("FileId");

                    b.HasIndex("SenderId");

                    b.ToTable("message");
                });

            modelBuilder.Entity("Backend.Models.NormUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("user_id");

                    b.Property<int>("Credit")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("credit");

                    b.Property<string>("Profile")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("profile");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable("norm_user");
                });

            modelBuilder.Entity("Backend.Models.ProdImage", b =>
                {
                    b.Property<long>("ImgFileId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("img_file_id");

                    b.Property<int>("ImgIndex")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("img_index");

                    b.Property<long>("ProductId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("product_id");

                    b.HasKey("ImgFileId");

                    b.HasIndex("ProductId");

                    b.ToTable("prod_image");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("product_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("category_id");

                    b.Property<string>("Info")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("info");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("release_date");

                    b.Property<int>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("user_id");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("product");
                });

            modelBuilder.Entity("Backend.Models.ProductView", b =>
                {
                    b.Property<long>("ViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("view_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ViewId"));

                    b.Property<long>("ProductId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("product_id");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ViewTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("view_time");

                    b.HasKey("ViewId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("product_view");
                });

            modelBuilder.Entity("Backend.Models.Purchase", b =>
                {
                    b.Property<long>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("purchase_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PurchaseId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("address_id");

                    b.Property<int>("BuyerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime?>("CancelTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("cancel_time");

                    b.Property<DateTime?>("CompleteTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("complete_time");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("create_time");

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("delivery_time");

                    b.Property<DateTime?>("PayTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("pay_time");

                    b.Property<long>("ProductId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("product_id");

                    b.Property<int>("ResponsibleForShip")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("responsible_for_ship");

                    b.Property<decimal>("ShippingFees")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("shipping_fees");

                    b.Property<DateTime?>("ShippingTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("shipping_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("status");

                    b.HasKey("PurchaseId");

                    b.HasIndex("AddressId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ProductId");

                    b.ToTable("purchase");
                });

            modelBuilder.Entity("Backend.Models.Refund", b =>
                {
                    b.Property<long>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("refund_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RefundId"));

                    b.Property<DateTime>("ApplyTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("apply_time");

                    b.Property<long>("PurchaseId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("purchase_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("reason");

                    b.Property<int>("ResponsibleForShip")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("responsible_for_ship");

                    b.Property<decimal>("ShippingFees")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("shipping_fees");

                    b.HasKey("RefundId");

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.ToTable("refund");
                });

            modelBuilder.Entity("Backend.Models.RefundReview", b =>
                {
                    b.Property<long>("RefundId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("refund_id")
                        .HasColumnOrder(0);

                    b.Property<int>("ReviewerType")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("reviewer_type")
                        .HasColumnOrder(1);

                    b.Property<string>("Info")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("info");

                    b.Property<int>("Result")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("result");

                    b.Property<DateTime>("ReviewTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("review_time");

                    b.HasKey("RefundId", "ReviewerType");

                    b.ToTable("refund_review");
                });

            modelBuilder.Entity("Backend.Models.RevImage", b =>
                {
                    b.Property<long>("ImgFileId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("img_file_id");

                    b.Property<int>("ImgIndex")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("img_index");

                    b.Property<int>("ReviewId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("review_id");

                    b.HasKey("ImgFileId");

                    b.HasIndex("ReviewId");

                    b.ToTable("rev_image");
                });

            modelBuilder.Entity("Backend.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("review_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Info")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("info");

                    b.Property<long>("PurchaseId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("purchase_id");

                    b.Property<int>("Rating")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("rating");

                    b.Property<DateTime>("ReviewTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("review_time");

                    b.HasKey("ReviewId");

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.ToTable("review");
                });

            modelBuilder.Entity("Backend.Models.SysInfo", b =>
                {
                    b.Property<int>("SysInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("sys_info_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SysInfoId"));

                    b.Property<string>("Detailed")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("detailed");

                    b.Property<DateTime>("ReleaseTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("release_time");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("user_id");

                    b.HasKey("SysInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("sys_info");
                });

            modelBuilder.Entity("Backend.Models.UpdatedFile", b =>
                {
                    b.Property<long>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("file_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FileId"));

                    b.Property<int>("ContentType")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("content_type");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("deleted_time");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("upload_time");

                    b.Property<int>("UploaderId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("uploader_id");

                    b.HasKey("FileId");

                    b.HasIndex("UploaderId");

                    b.ToTable("files");
                });

            modelBuilder.Entity("Backend.Models.WorkOrder", b =>
                {
                    b.Property<long>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("work_order_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkOrderId"));

                    b.Property<int?>("AccusedId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("accused_id");

                    b.Property<int?>("AdminId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("create_time");

                    b.Property<string>("Info")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("info");

                    b.Property<int>("InitiatorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("initiator_id");

                    b.Property<long?>("ProductId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("product_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("reason");

                    b.Property<string>("Response")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("response");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("response_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("type");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("AccusedId");

                    b.HasIndex("AdminId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("ProductId");

                    b.ToTable("work_order");
                });

            modelBuilder.Entity("Backend.Models.Address", b =>
                {
                    b.HasOne("Backend.Models.NormUser", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.AdminUser", b =>
                {
                    b.HasOne("Backend.Models.BaseUser", "BaseUser")
                        .WithOne("AdminUser")
                        .HasForeignKey("Backend.Models.AdminUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseUser");
                });

            modelBuilder.Entity("Backend.Models.Announcement", b =>
                {
                    b.HasOne("Backend.Models.AdminUser", "Admin")
                        .WithMany("Announcements")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Backend.Models.BaseUser", b =>
                {
                    b.HasOne("Backend.Models.UpdatedFile", "AvatarFile")
                        .WithMany()
                        .HasForeignKey("AvatarFileId");

                    b.Navigation("AvatarFile");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.HasOne("Backend.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Backend.Models.Collection", b =>
                {
                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("Collections")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.NormUser", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Conversation", b =>
                {
                    b.HasOne("Backend.Models.NormUser", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Message", b =>
                {
                    b.HasOne("Backend.Models.UpdatedFile", "AttachedFile")
                        .WithMany()
                        .HasForeignKey("FileId");

                    b.HasOne("Backend.Models.NormUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttachedFile");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Backend.Models.NormUser", b =>
                {
                    b.HasOne("Backend.Models.BaseUser", "BaseUser")
                        .WithOne("NormUser")
                        .HasForeignKey("Backend.Models.NormUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseUser");
                });

            modelBuilder.Entity("Backend.Models.ProdImage", b =>
                {
                    b.HasOne("Backend.Models.UpdatedFile", "ImgFile")
                        .WithMany()
                        .HasForeignKey("ImgFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImgFile");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.NormUser", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Backend.Models.ProductView", b =>
                {
                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("Views")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.NormUser", "User")
                        .WithMany("Views")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Purchase", b =>
                {
                    b.HasOne("Backend.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.NormUser", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Buyer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Refund", b =>
                {
                    b.HasOne("Backend.Models.Purchase", "Purchase")
                        .WithOne("Refund")
                        .HasForeignKey("Backend.Models.Refund", "PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Backend.Models.RefundReview", b =>
                {
                    b.HasOne("Backend.Models.Refund", "Refund")
                        .WithMany("RefundReviews")
                        .HasForeignKey("RefundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Refund");
                });

            modelBuilder.Entity("Backend.Models.RevImage", b =>
                {
                    b.HasOne("Backend.Models.UpdatedFile", "ImgFile")
                        .WithMany()
                        .HasForeignKey("ImgFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Review", "Review")
                        .WithMany("Images")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImgFile");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Backend.Models.Review", b =>
                {
                    b.HasOne("Backend.Models.Purchase", "Purchase")
                        .WithOne("Review")
                        .HasForeignKey("Backend.Models.Review", "PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Backend.Models.SysInfo", b =>
                {
                    b.HasOne("Backend.Models.NormUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.UpdatedFile", b =>
                {
                    b.HasOne("Backend.Models.BaseUser", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Backend.Models.WorkOrder", b =>
                {
                    b.HasOne("Backend.Models.NormUser", "Accused")
                        .WithMany()
                        .HasForeignKey("AccusedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.AdminUser", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.NormUser", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Accused");

                    b.Navigation("Admin");

                    b.Navigation("Initiator");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.AdminUser", b =>
                {
                    b.Navigation("Announcements");
                });

            modelBuilder.Entity("Backend.Models.BaseUser", b =>
                {
                    b.Navigation("AdminUser");

                    b.Navigation("NormUser");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Backend.Models.NormUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Collections");

                    b.Navigation("Products");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Images");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("Backend.Models.Purchase", b =>
                {
                    b.Navigation("Refund");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Backend.Models.Refund", b =>
                {
                    b.Navigation("RefundReviews");
                });

            modelBuilder.Entity("Backend.Models.Review", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
